import * as THREE from "three";
import { OrbitControls } from "three/addons/controls/OrbitControls.js";

const $=id=>document.getElementById(id);
let scene,camera,renderer,controls,clock,ground,unitGroup,fxGroup;
let units=[],selectedUnit=null,currentCountry="USA",paused=false,speed=1,day=1,month=1,year=1940,moveMode=false,attackMode=false;
let money=12500,oil=850,steel=1250,food=1600,manpower=85000,weather="CLEAR",mapLayer="MILITARY";
let tax=22,stability=78,political=120,construction=6,spy=24,intel=48,counterIntel=42;
let factories={civilian:18,military:14,naval:5};
let production={TANK:{factories:4,progress:67,eff:74,cost:800,steel:80},INFANTRY:{factories:5,progress:42,eff:82,cost:350,steel:35},ARTILLERY:{factories:3,progress:55,eff:68,cost:600,steel:65},AIR:{factories:2,progress:31,eff:59,cost:1100,steel:90}};
let tech={INFANTRY:{name:"Infantry Weapons",progress:54,bonus:"+8% infantry attack",active:false},ARMOR:{name:"Advanced Armor",progress:32,bonus:"+10% tank attack",active:false},ARTILLERY:{name:"Modern Artillery",progress:48,bonus:"+8% artillery damage",active:false},AIR:{name:"Fighter Interceptors",progress:28,bonus:"+12% air defense",active:false},INDUSTRY:{name:"Industrial Methods",progress:71,bonus:"+1 civilian factory",active:false},LOGISTICS:{name:"Motorized Logistics",progress:42,bonus:"-10% supply use",active:false},ELECTRONICS:{name:"Field Electronics",progress:18,bonus:"+10 intel",active:false}};
let diplomacy={GERMANY:-65,UK:18,JAPAN:-42,USSR:-8,FRANCE:35};
const nation={USA:["🇺🇸","United States"],GERMANY:["🇩🇪","Germany"],UK:["🇬🇧","United Kingdom"],JAPAN:["🇯🇵","Japan"],USSR:["☭","Soviet Union"],FRANCE:["🇫🇷","France"]};
const mapColors={MILITARY:0x596b58,POLITICAL:0x58667d,TERRAIN:0x52634d,SUPPLY:0x4e6e5a,RESOURCES:0x75633c,INTEL:0x5d4c6b};
const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();

function load(){
  const s=localStorage.getItem("ww_v2"); if(!s)return;
  try{const d=JSON.parse(s);Object.assign({},{}) ; ["money","oil","steel","food","manpower","tax","stability","political","construction","spy","intel","counterIntel","day","month","year","speed","weather","mapLayer","currentCountry"].forEach(k=>{if(d[k]!==undefined)eval(k+"=d[k]")});}catch(e){console.warn(e)}
}
function save(){localStorage.setItem("ww_v2",JSON.stringify({money,oil,steel,food,manpower,tax,stability,political,construction,spy,intel,counterIntel,day,month,year,speed,weather,mapLayer,currentCountry}));toast("Campaign saved");}
function loading(p,t){if($("loadingProgress"))$("loadingProgress").style.width=p+"%";if($("loadingStatus"))$("loadingStatus").textContent=t;}
async function init(){
 loading(15,"Initializing command system..."); setup3D(); loading(35,"Generating battlefield..."); terrain(); loading(55,"Deploying forces..."); deploy(); loading(75,"Loading strategy systems..."); load(); ui(); loading(100,"Battlefield ready."); setTimeout(()=>$("loadingScreen")?.classList.add("hidden"),500); loop();
}
function setup3D(){
 const c=$("gameCanvas"); scene=new THREE.Scene();scene.background=new THREE.Color(0x071015);scene.fog=new THREE.Fog(0x071015,70,430);
 camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,1000);camera.position.set(0,82,86);
 renderer=new THREE.WebGLRenderer({canvas:c,antialias:true,powerPreference:"high-performance"});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;
 scene.add(new THREE.HemisphereLight(0xbfcbd0,0x182018,1.4));const sun=new THREE.DirectionalLight(0xffdfad,2);sun.position.set(-80,140,60);sun.castShadow=true;scene.add(sun);
 controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=20;controls.maxDistance=240;controls.maxPolarAngle=Math.PI*.47;controls.target.set(0,0,0);clock=new THREE.Clock();unitGroup=new THREE.Group();fxGroup=new THREE.Group();scene.add(unitGroup,fxGroup);
 addEventListener("resize",()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
 c.addEventListener("pointerdown",worldClick);
}
function terrain(){
 const g=new THREE.PlaneGeometry(360,360,100,100),p=g.attributes.position;for(let i=0;i<p.count;i++){let x=p.getX(i),y=p.getY(i);p.setZ(i,Math.sin(x*.05)*2+Math.cos(y*.06)*1.7+Math.sin((x+y)*.025)*3)}g.computeVertexNormals();
 ground=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:mapColors[mapLayer],roughness:.96}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;ground.userData.ground=true;scene.add(ground);
 const grid=new THREE.GridHelper(360,72,0x68715f,0x30382f);grid.material.transparent=true;grid.material.opacity=.08;scene.add(grid);
 const water=new THREE.Mesh(new THREE.PlaneGeometry(520,520),new THREE.MeshStandardMaterial({color:0x164659,transparent:true,opacity:.55,roughness:.2}));water.rotation.x=-Math.PI/2;water.position.y=-4;scene.add(water);
 for(let i=0;i<65;i++){const m=new THREE.Mesh(new THREE.ConeGeometry(3+Math.random()*6,9+Math.random()*18,7),new THREE.MeshStandardMaterial({color:0x394039,roughness:1}));m.position.set((Math.random()-.5)*320,5+Math.random()*7,(Math.random()-.5)*320);m.castShadow=true;scene.add(m)}
 for(let i=0;i<150;i++){const g2=new THREE.Group(),t=new THREE.Mesh(new THREE.CylinderGeometry(.12,.18,1.3,5),new THREE.MeshStandardMaterial({color:0x493a2a})),c=new THREE.Mesh(new THREE.ConeGeometry(.7,2.5,7),new THREE.MeshStandardMaterial({color:0x263d28}));t.position.y=.65;c.position.y=2;g2.add(t,c);g2.position.set((Math.random()-.5)*330,.3,(Math.random()-.5)*330);g2.scale.setScalar(.7+Math.random()*.8);scene.add(g2)}
 createLine(0xb0a66f,[[ -150,-90],[-70,-125],[10,-100],[60,-60],[-10,-20],[-150,-90]]);createLine(0xb0a66f,[[-100,35],[-40,10],[20,55],[-30,120],[-120,95],[-100,35]]);createLine(0xb33f3f,[[15,-40],[45,-32],[75,-38],[105,-28],[135,-35]]);
}
function createLine(color,pts){const l=new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts.map(a=>new THREE.Vector3(a[0],.4,a[1]))),new THREE.LineBasicMaterial({color,transparent:true,opacity:.45}));scene.add(l)}
function unit(name,type,x,z,friendly=true){
 const g=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color:friendly?(type==="TANK"?0x566b4f:0x60715a):(type==="TANK"?0x633b36:0x68453f),roughness:.75});
 if(type==="TANK"){let b=new THREE.Mesh(new THREE.BoxGeometry(5,1.8,3.2),mat),t=new THREE.Mesh(new THREE.CylinderGeometry(1.25,1.35,.8,12),mat),c=new THREE.Mesh(new THREE.BoxGeometry(.35,.35,3.8),new THREE.MeshStandardMaterial({color:0x202521,metalness:.5}));b.position.y=1.1;t.position.y=2.2;c.position.set(0,2.3,2);g.add(b,t,c)}
 else if(type==="AIR"){let f=new THREE.Mesh(new THREE.CapsuleGeometry(.7,4,5,10),mat),w=new THREE.Mesh(new THREE.BoxGeometry(5,.2,1.3),mat);f.rotation.x=Math.PI/2;g.add(f,w);g.position.y=8}
 else {let b=new THREE.Mesh(new THREE.CapsuleGeometry(.65,1.4,5,8),mat),h=new THREE.Mesh(new THREE.SphereGeometry(.48,10,10),new THREE.MeshStandardMaterial({color:0x8c6c50}));b.position.y=1.4;h.position.y=2.7;g.add(b,h)}
 g.position.x=x;g.position.z=z;g.castShadow=true;unitGroup.add(g);const u={id:crypto.randomUUID?.()||Math.random().toString(36),name,type,friendly,object:g,hp:100,organization:type==="AIR"?88:100,morale:type==="TANK"?82:85,strength:type==="TANK"?85:type==="AIR"?75:70,readiness:96,supply:92,attack:type==="TANK"?24:type==="AIR"?30:16,defense:type==="TANK"?20:17,speed:type==="TANK"?18:type==="AIR"?35:12,state:"READY",destination:null};g.userData.unit=u;units.push(u);return u;
}
function deploy(){units=[];unit("1st Armored Division","TANK",-30,12);unit("2nd Infantry Division","INFANTRY",-18,20);unit("3rd Infantry Division","INFANTRY",-5,28);unit("Air Wing Alpha","AIR",15,12);unit("Enemy Armor Group","TANK",45,-20,false);unit("Enemy Infantry Corps","INFANTRY",35,-5,false);unit("Enemy Defense Force","INFANTRY",55,12,false);unit("Enemy Air Wing","AIR",65,-18,false);mini();}
function ui(){
 $("countryName").textContent=nation[currentCountry][1];$("countryFlag").textContent=nation[currentCountry][0];update();
 document.querySelectorAll(".panel-button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".panel-button").forEach(x=>x.classList.remove("active"));b.classList.add("active");openPanel(b.dataset.panel)});
 $("closePanel")?.addEventListener("click",()=>$("mainPanel").classList.remove("open"));$("closeUnit")?.addEventListener("click",()=>{selectedUnit=null;$("unitPanel").classList.remove("open")});
 $("pauseBtn")?.addEventListener("click",()=>{paused=!paused;$("pauseBtn").textContent=paused?"▶":"Ⅱ"});$("speedBtn")?.addEventListener("click",()=>{speed=speed===1?2:speed===2?4:1;$("speedBtn").textContent=speed+"×"});
 $("zoomIn")?.addEventListener("click",()=>camera.position.multiplyScalar(.85));$("zoomOut")?.addEventListener("click",()=>camera.position.multiplyScalar(1.15));$("resetCamera")?.addEventListener("click",()=>{camera.position.set(0,82,86);controls.target.set(0,0,0)}); $("moveCommand")?.addEventListener("click",()=>{if(selectedUnit){moveMode=true;attackMode=false;toast("Tap terrain to move this unit")}});$("attackCommand")?.addEventListener("click",()=>{if(selectedUnit){attackMode=true;moveMode=false;toast("Tap an enemy unit to attack")}});
 $("defendCommand")?.addEventListener("click",()=>order("DEFEND"));$("holdCommand")?.addEventListener("click",()=>order("HOLD"));$("retreatCommand")?.addEventListener("click",()=>order("RETREAT"));$("airstrikeCommand")?.addEventListener("click",()=>order("AIRSTRIKE"));
 document.querySelectorAll(".country-card").forEach(b=>b.onclick=()=>{currentCountry=b.dataset.country;$("countryModal")?.classList.remove("open");$("countryName").textContent=nation[currentCountry][1];$("countryFlag").textContent=nation[currentCountry][0];update();toast("Nation selected: "+nation[currentCountry][1])});
 $("tutorialNext")?.addEventListener("click",()=>$("tutorial")?.remove());$("closeCountryModal")?.addEventListener("click",()=>$("countryModal")?.classList.remove("open"));
}
function update(){for(const [id,val] of Object.entries({money,oil,steel,food,manpower}))if($(id))$(id).textContent=Math.floor(val).toLocaleString();if($("gameDate"))$("gameDate").textContent=`${year} • ${["JAN","FEB","MAR","APR","MAY","JUN","JUL","AUG","SEP","OCT","NOV","DEC"][month-1]} ${String(day).padStart(2,"0")}`;mini();}
function worldClick(e){
 const r=renderer.domElement.getBoundingClientRect();mouse.x=((e.clientX-r.left)/r.width)*2-1;mouse.y=-((e.clientY-r.top)/r.height)*2+1;ray.setFromCamera(mouse,camera);const hits=ray.intersectObjects(unitGroup.children,true);
 if(hits.length){let o=hits[0].object;while(o.parent&&!o.userData.unit)o=o.parent;if(o.userData.unit){const u=o.userData.unit;if(attackMode&&selectedUnit&&u!==selectedUnit&&!u.friendly){combat(selectedUnit,u);return}select(u);return}}
 const g=ray.intersectObject(ground);if(g.length&&selectedUnit&&moveMode){selectedUnit.destination=g[0].point.clone();selectedUnit.state="MOVING";moveMode=false;toast(selectedUnit.name+" moving")}
}
function select(u){selectedUnit=u;$("unitPanel")?.classList.add("open");$("selectedUnitType").textContent=u.type+" • "+(u.friendly?"FRIENDLY":"HOSTILE");$("selectedUnitName").textContent=u.name;$("unitStats").innerHTML=`${bar("Strength",u.strength)}${bar("Organization",u.organization)}${bar("Morale",u.morale)}${bar("Readiness",u.readiness)}${bar("Supply",u.supply)}${stat("State",u.state)}${stat("Speed",u.speed)}`;}
function bar(a,v){return `<div class="unit-stat"><span>${a}</span><div class="progress"><i style="width:${Math.max(0,Math.min(100,v))}%"></i></div><b>${Math.round(v)}%</b></div>`}
function stat(a,v){return `<div class="stat-row"><span>${a}</span><b>${v}</b></div>`}
function order(type){if(!selectedUnit)return;selectedUnit.state=type;selectedUnit.destination=null;toast(selectedUnit.name+" — "+type);select(selectedUnit)}
function combat(a,b){if(!a||!b)return;let atk=a.attack+a.strength*.15+Math.random()*12,def=b.defense+b.strength*.1+Math.random()*10,damage=Math.max(5,atk-def*.55);b.hp-=damage;b.organization-=damage*.45;a.organization-=Math.max(2,damage*.18);a.morale-=1;b.morale-=2;toast(`${a.name} attacked ${b.name}`);if(b.hp<=0||b.organization<=0){b.state="DESTROYED";b.object.visible=false;toast(b.name+" destroyed")}select(a)}
function openPanel(type){const p=$("mainPanel"),c=$("panelContent");p.classList.add("open");const v=panels[type]||panels.overview;$("panelTitle").textContent=v.title;$("panelKicker").textContent=v.kicker;c.innerHTML=v.html();bindPanel(type)}
const panels={
 overview:{title:"World Overview",kicker:"STRATEGIC COMMAND",html:()=>`<div class="info-card"><h3>Global Situation</h3>${stat("Active Forces",units.filter(u=>u.friendly).length)}${stat("Enemy Forces",units.filter(u=>!u.friendly&&u.state!=="DESTROYED").length)}${stat("Threat Level",threat())}${stat("Weather",weather)}${stat("Map Layer",mapLayer)}</div><div class="info-card"><h3>Map Layers</h3>${["MILITARY","POLITICAL","TERRAIN","SUPPLY","RESOURCES","INTEL"].map(x=>`<button class="action-btn layer" data-layer="${x}">${x}</button>`).join("")}</div><div class="info-card"><h3>Strategic Status</h3>${bar("Army Strength",avg("strength"))}${bar("Organization",avg("organization"))}${bar("Morale",avg("morale"))}${bar("Readiness",avg("readiness"))}</div>`},
 army:{title:"Army Command",kicker:"MILITARY COMMAND",html:()=>`<div class="info-card"><h3>Available Forces ${units.filter(u=>u.friendly).length}/12</h3>${units.filter(u=>u.friendly&&u.state!=="DESTROYED").map(u=>`<button class="action-btn usel" data-id="${u.id}" style="text-align:left">${u.type==="TANK"?"🛡️":u.type==="AIR"?"✈️":"🪖"} ${u.name} — ${u.state}</button>`).join("")}</div><div class="info-card"><h3>Army Statistics</h3>${bar("Strength",avg("strength"))}${bar("Organization",avg("organization"))}${bar("Morale",avg("morale"))}${bar("Readiness",avg("readiness"))}${stat("Manpower",manpower.toLocaleString())}</div><div class="info-card"><h3>Templates</h3>${["Standard Infantry","Armored Spearhead","Combined Arms","Airborne Assault"].map(x=>stat(x,"READY")).join("")}</div><div class="info-card"><h3>Doctrine</h3>${stat("Land","MOBILE WARFARE")}${stat("Air","FIGHTER SUPERIORITY")}${stat("Logistics","MOTORIZE SUPPLY")}</div>`},
 economy:{title:"Economy",kicker:"NATIONAL ECONOMY",html:()=>`<div class="info-card"><h3>Resources</h3>${stat("Money",Math.floor(money).toLocaleString())}${stat("Oil",Math.floor(oil).toLocaleString())}${stat("Steel",Math.floor(steel).toLocaleString())}${stat("Food",Math.floor(food).toLocaleString())}${stat("Manpower",Math.floor(manpower).toLocaleString())}</div><div class="info-card"><h3>Stability</h3>${bar("National Stability",stability)}${stat("Tax Rate",tax+"%")}${stat("Political Power",political)}${stat("Construction",construction)}</div><button class="action-btn" id="taxdown">LOWER TAX — 2%</button><button class="action-btn" id="taxup">RAISE TAX — 2%</button><button class="action-btn" id="invest">INVEST IN INDUSTRY — $1000</button><button class="action-btn" id="factory">BUILD MILITARY FACTORY — 4 CONSTRUCTION</button>`},
 production:{title:"Military Production",kicker:"INDUSTRIAL COMMAND",html:()=>`<div class="info-card"><h3>Factories</h3>${stat("Civilian",factories.civilian)}${stat("Military",factories.military)}${stat("Naval",factories.naval)}</div><div class="info-card">${Object.entries(production).map(([k,p])=>`<div>${stat(k,p.factories+" factories • "+p.eff+"% efficiency")}${bar("Progress",p.progress)}<button class="action-btn prod" data-type="${k}">ASSIGN +1 FACTORY</button></div>`).join("")}</div><button class="action-btn" id="ptank">PRODUCE TANK — $800 / 80 STEEL</button><button class="action-btn" id="pinf">PRODUCE INFANTRY — $350 / 35 STEEL</button><button class="action-btn" id="part">PRODUCE ARTILLERY — $600 / 65 STEEL</button><button class="action-btn" id="pair">PRODUCE AIRCRAFT — $1100 / 90 STEEL</button>`},
 research:{title:"Technology",kicker:"RESEARCH COMMAND",html:()=>`<div class="info-card"><h3>Research Slots: 3</h3>${Object.entries(tech).map(([k,t])=>`<div>${stat(t.name,t.active?Math.round(t.progress)+"%":"AVAILABLE")}${bar(t.bonus,t.progress)}<button class="action-btn research" data-tech="${k}">${t.active?"ADVANCE":"START RESEARCH"}</button></div>`).join("")}</div>`},
 diplomacy:{title:"Diplomacy",kicker:"FOREIGN AFFAIRS",html:()=>`<div class="info-card">${Object.entries(diplomacy).map(([k,v])=>`<div style="padding:8px 0;border-bottom:1px solid rgba(255,255,255,.05)">${stat(nation[k][0]+" "+nation[k][1],v)}<button class="action-btn dip" data-country="${k}">IMPROVE RELATIONS</button><button class="action-btn war" data-country="${k}">${v<-50?"DECLARE WAR":"NEGOTIATE PACT"}</button></div>`).join("")}</div>`},
 intel:{title:"Intelligence",kicker:"INTELLIGENCE COMMAND",html:()=>`<div class="info-card">${bar("Intel Level",intel)}${bar("Spy Network",spy)}${bar("Counter Intelligence",counterIntel)}${stat("Enemy Armor",units.filter(u=>!u.friendly&&u.type==="TANK").length)}${stat("Enemy Air",units.filter(u=>!u.friendly&&u.type==="AIR").length)}</div><button class="action-btn" id="recon">RUN RECON — $250</button><button class="action-btn" id="spybtn">EXPAND SPY NETWORK — $400</button><button class="action-btn" id="counter">COUNTER-INTELLIGENCE — $350</button>`},
 settings:{title:"Settings",kicker:"SYSTEM CONTROL",html:()=>`<div class="info-card">${stat("Weather",weather)}${stat("Map Layer",mapLayer)}${stat("Game Speed",speed+"×")}</div><button class="action-btn" id="weather">CHANGE WEATHER</button><button class="action-btn" id="save">SAVE CAMPAIGN</button><button class="action-btn" id="load2">LOAD CAMPAIGN</button><button class="action-btn" id="reset">RESET CAMERA</button>`}
};
function bindPanel(){
 document.querySelectorAll(".layer").forEach(b=>b.onclick=()=>setLayer(b.dataset.layer));document.querySelectorAll(".usel").forEach(b=>b.onclick=()=>{let u=units.find(x=>x.id==b.dataset.id);if(u)select(u)});
 $("taxdown")?.addEventListener("click",()=>{tax=Math.max(5,tax-2);toast("Tax reduced");update()});$("taxup")?.addEventListener("click",()=>{tax=Math.min(50,tax+2);toast("Tax increased");update()});$("invest")?.addEventListener("click",()=>{if(money>=1000){money-=1000;factories.civilian++;stability=Math.min(100,stability+2);toast("Industrial investment complete");update()}else toast("Not enough money")});$("factory")?.addEventListener("click",()=>{if(construction>=4){construction-=4;factories.military++;toast("Military factory built");update()}else toast("Need 4 construction points")});
 document.querySelectorAll(".prod").forEach(b=>b.onclick=()=>assignFactory(b.dataset.type));["TANK","INFANTRY","ARTILLERY","AIR"].forEach((k,i)=>$([ "ptank","pinf","part","pair"][i])?.addEventListener("click",()=>produce(k)));
 document.querySelectorAll(".research").forEach(b=>b.onclick=()=>researchTech(b.dataset.tech));document.querySelectorAll(".dip").forEach(b=>b.onclick=()=>improveDip(b.dataset.country));document.querySelectorAll(".war").forEach(b=>b.onclick=()=>dipAction(b.dataset.country));
 $("recon")?.addEventListener("click",recon);$("spybtn")?.addEventListener("click",expandSpy);$("counter")?.addEventListener("click",counter);$("weather")?.addEventListener("click",changeWeather);$("save")?.addEventListener("click",save);$("load2")?.addEventListener("click",()=>{load();update();toast("Campaign loaded")});$("reset")?.addEventListener("click",()=>{camera.position.set(0,82,86);controls.target.set(0,0,0)});
}
function setLayer(l){mapLayer=l;ground.material.color.setHex(mapColors[l]);toast("Map layer: "+l);mini()}
function assignFactory(k){if(factories.military>Object.values(production).reduce((a,p)=>a+p.factories,0)){production[k].factories++;toast(k+" factory assigned");openPanel("production")}else toast("No military factories available")}
function produce(k){let p=production[k];if(money>=p.cost&&steel>=p.steel){money-=p.cost;steel-=p.steel;p.progress=Math.min(100,p.progress+18);toast(k+" production ordered");update()}else toast("Insufficient resources")}
function researchTech(k){let t=tech[k];t.active=true;t.progress=Math.min(100,t.progress+8);political=Math.max(0,political-10);if(t.progress>=100){t.active=false;toast(t.name+" completed")}else toast("Research advanced: "+t.name);openPanel("research");update()}
function improveDip(k){if(political<15){toast("Need political power");return}political-=15;diplomacy[k]=Math.min(100,diplomacy[k]+8);toast("Relations improved with "+nation[k][1]);openPanel("diplomacy")}
function dipAction(k){diplomacy[k]=Math.max(-100,diplomacy[k]-20);toast("Diplomatic tension rising with "+nation[k][1]);openPanel("diplomacy")}
function recon(){if(money<250){toast("Not enough money");return}money-=250;intel=Math.min(100,intel+10);units.filter(u=>!u.friendly).forEach(u=>u.readiness=Math.max(0,u.readiness-0));toast("Recon complete: enemy positions updated");update()}
function expandSpy(){if(money<400){toast("Not enough money");return}money-=400;spy=Math.min(100,spy+12);intel=Math.min(100,intel+4);toast("Spy network expanded");update()}
function counter(){if(money<350){toast("Not enough money");return}money-=350;counterIntel=Math.min(100,counterIntel+12);toast("Counter-intelligence improved");update()}
function changeWeather(){setWeather(weather==="CLEAR"?"RAIN":weather==="RAIN"?"SNOW":"CLEAR")}
function setWeather(w){weather=w;toast("Weather: "+w);}
function avg(k){let a=units.filter(u=>u.friendly&&u.state!=="DESTROYED");return a.length?Math.round(a.reduce((s,u)=>s+(u[k]||0),0)/a.length):0}
function threat(){let e=units.filter(u=>!u.friendly&&u.state!=="DESTROYED").reduce((s,u)=>s+u.strength,0),f=units.filter(u=>u.friendly).reduce((s,u)=>s+u.strength,0);return e>f?"HIGH":e>f*.75?"MEDIUM":"LOW"}
function toast(t){let e=$("toast");if(!e)return;e.textContent=t;e.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove("show"),1800)}
function mini(){const m=$("miniUnits");if(!m)return;m.innerHTML="";units.filter(u=>u.state!=="DESTROYED").forEach(u=>{const d=document.createElement("i");d.style.position="absolute";d.style.width="5px";d.style.height="5px";d.style.borderRadius="50%";d.style.background=u.friendly?"#55d18a":"#e45d5d";d.style.left=(50+u.object.position.x/3.8)+"%";d.style.top=(50+u.object.position.z/3.8)+"%";m.appendChild(d)})}
function orderMove(u){if(!u.destination)return;const v=new THREE.Vector3().subVectors(u.destination,u.object.position),dist=v.length();if(dist<1){u.destination=null;u.state="HOLDING";return}v.normalize();u.object.position.addScaledVector(v,u.speed*.018*speed);if(u.type==="AIR")u.object.position.y=8}
function tick(dt){if(paused)return;let rate=dt*speed;money+=rate*(2.8+tax*.12);oil+=rate*.18;steel+=rate*.25;food+=rate*.3;manpower+=rate*4.5;political=Math.min(999,political+rate*.035);construction=Math.min(20,construction+rate*.01);
 units.forEach(u=>{if(u.state==="MOVING")orderMove(u);if(u.state==="HOLD")u.organization=Math.min(100,u.organization+rate*.7);u.supply=Math.max(0,Math.min(100,u.supply+rate*.15));});
 if(Math.random()<dt*speed*.08)ai();update();}
function ai(){const enemies=units.filter(u=>!u.friendly&&u.state!=="DESTROYED"),friends=units.filter(u=>u.friendly&&u.state!=="DESTROYED");enemies.forEach(e=>{let f=friends.sort((a,b)=>a.object.position.distanceTo(e.object.position)-b.object.position.distanceTo(e.object.position))[0];if(f&&e.object.position.distanceTo(f.object.position)<25)combat(e,f);else if(f){e.destination=f.object.position.clone();e.state="MOVING"}})}
function dateTick(){if(paused)return;day++;if(day>30){day=1;month++;if(month>12){month=1;year++}};if($("statusText"))$("statusText").textContent=weather==="CLEAR"?"All systems operational":weather+" conditions across theater";if($("battleStatus"))$("battleStatus").textContent=threat()==="HIGH"?"ACTIVE FRONTLINE THREAT":"FRONTLINE STABLE"}
function loop(){requestAnimationFrame(loop);const dt=Math.min(.05,clock.getDelta());tick(dt);if(!paused&&clock.elapsedTime>0){if(!window.__date||clock.elapsedTime-window.__date>1){window.__date=clock.elapsedTime;dateTick()}};controls.update();renderer.render(scene,camera)}

init();